#!/usr/bin/env bash

TESTS_FILESYS_SMALL_FILES="sm-create sm-full sm-random sm-seq-block sm-seq-random"
TESTS_FILESYS_LARGE_FILES="lg-create lg-full lg-random lg-seq-block lg-seq-random"
TESTS_FILESYS_MULTI_PROGRAM="syn-read syn-write syn-remove"
TESTS_FILESYS="$TESTS_FILESYS_SMALL_FILES $TESTS_FILESYS_LARGE_FILES $TESTS_FILESYS_MULTI_PROGRAM"

bash ../execute-tests "filesys/base" "$TESTS_FILESYS"
