#!/usr/bin/env bash

TESTS_MFLQ_SCHEDULER="mlfqs-load-1 mlfqs-load-60 mlfqs-load-avg mlfqs-recent-1 mlfqs-fair-2 mlfqs-fair-20 mlfqs-nice-2 mlfqs-nice-10 mlfqs-block"

bash ../execute-tests "threads" "$TESTS_MFLQ_SCHEDULER"
