name: Execute pintos tests

on:
  push:
    branches:
      - "proyecto01/priority-scheduling"

jobs:
  tests:
    runs-on: ubuntu-latest
    container:
      image: alainchevanier/so-20231-pintos
      volumes:
        -  ${{ github.workspace }}:/app
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Compile
        run: |
          cd /app/src/threads
          make
      - name: Run tests - Alarm Clock
        run: |
          cd /app/src/threads
          bash execute-tests-alarm-clock
      - name: Run tests - Priority Scheduling
        run: |
          cd /app/src/threads
          bash execute-tests-priority-scheduling
