name: Execute pintos tests

on:
  push:
    branches:
      - "proyecto02/filesys-syscalls"

jobs:
  tests:
    runs-on: ubuntu-latest
    container:
      image: alainchevanier/so-20231-pintos
      volumes:
        -  ${{ github.workspace }}:/app
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Compile
        run: |
          cd /app/src/userprog
          make
      - name: Run tests - Argument Passing
        run: |
          cd /app/src/userprog
          bash execute-tests-argument-passing
      - name: Run tests - Process Control Syscalls
        run: |
          cd /app/src/userprog
          bash execute-tests-process-control-syscalls
      - name: Run tests - File System Syscalls
        run: |
          cd /app/src/userprog
          bash execute-tests-filesys-syscalls
      - name: Run tests - File System
        run: |
          cd /app/src/userprog
          bash execute-tests-filesys
      - name: Run tests - Read Only Executables
        run: |
          cd /app/src/userprog
          bash execute-tests-rox
